/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/phanik/oEPC/trunk/openair2/RRC/LITE/MESSAGES/asn1c/ASN1_files/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "SystemInformation-r8-IEs-sib-TypeAndInfo-Member.h"

static asn_per_constraints_t asn_PER_type_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib2),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib3),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib4),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib5),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib6),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib7),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib7"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib8),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib8"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib9),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib9"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib10),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, choice.sib11),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationBlockType11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib11"
		},
};
static asn_TYPE_tag2member_t asn_MAP_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sib2 at 687 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sib3 at 688 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sib4 at 689 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sib5 at 690 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sib6 at 691 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sib7 at 692 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sib8 at 693 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* sib9 at 694 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* sib10 at 695 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* sib11 at 696 */
};
static asn_CHOICE_specifics_t asn_SPC_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_specs_1 = {
	sizeof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member),
	offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, _asn_ctx),
	offsetof(struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member, present),
	sizeof(((struct SystemInformation_r8_IEs_sib_TypeAndInfo_Member *)0)->present),
	asn_MAP_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_tag2el_1,
	10,	/* Count of tags in the map */
	0,
	10	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformation_r8_IEs_sib_TypeAndInfo_Member = {
	"SystemInformation-r8-IEs-sib-TypeAndInfo-Member",
	"SystemInformation-r8-IEs-sib-TypeAndInfo-Member",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_constr_1,
	asn_MBR_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_1,
	10,	/* Elements count */
	&asn_SPC_SystemInformation_r8_IEs_sib_TypeAndInfo_Member_specs_1	/* Additional specs */
};

